config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, {
    skip: [:registrations]
  }
  #resources :home, only: [:index]
  if Rails.application.secrets.try(:maintenance).blank? || !Rails.application.secrets.maintenance
    root 'people#councillors'
  else
    root 'static_pages#maintance'
  end
  
  resources :people, only: [:index, :show] do
    member do
      post :contact
      put :hide
      put :unhide
    end
    collection do
      get :councillors
      get :councillors_not_work
      get :councillors_other
      get :directors
      get :directors_not_work
      get :temporary_workers
      get :public_workers
      get :labours
      get :spokespeople
    end
  end

  concern :mailer_log do
    get :show_mailer, on: :member
    post :send_mailer, on: :member
  end
  
  namespace :admin do
    resources :data_exports, only: [:index] 
    resources :notifications, only: [:show] do
      get :profiles, on: :collection
      get :assets, on: :collection
      get :activities, on: :collection
      get :person, on: :collection
      get :profiles_historic, on: :collection
      get :assets_historic, on: :collection
      get :activities_historic, on: :collection
      get :person_historic, on: :collection
      get :permit, on: :member
      get :reject, on: :member
      get :publicable, on: :member
      get :update_data, on: :collection
      get :insert_reject, on: :member
      get :forward, on: :member
    end
    resources :preferences, only: [:index]
    resources :manage_emails
    resources :data_preferences do
      post :update_all, on: :collection
    end
    root to: "dashboard#index"
    resources :text_contents
    resources :corporations
    resources :electoral_lists
    resources :delete_data, only: [:show, :index] do
      post :delete_information, on: :collection
    end
    resources :profile_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy]
    resources :assets_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :activities_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :people, except: :show do
      get :show_hide, on: :member
      get :show_unhide, on: :member
      get :portrait_delete, on: :member
      get :audits, on: :member
      put :hide
      put :unhide
      get :download, on: :collection
    end
    resources :statistics, only: [:index] do
      get :profiles, on: :collection
      get :councillors, on: :collection
      get :directors, on: :collection
      get :update_data, on: :collection
    end
  end

  # static pages
  #get "/welcome", to: "home#welcome"
  #get "/maintance", to: "static_pages#maintance"
  get "/accessibility", to: "static_pages#accessibility"
  get "/conditions", to: "static_pages#conditions"
  get "/privacy", to: "static_pages#privacy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect('/')
  get "*missing" => redirect('/') 
end

app/models/corporation.rb
require 'active_record/diff'
class Corporation < ActiveRecord::Base
    include ActiveRecord::Diff
    diff :exclude => [:created_at, :updated_at]
    has_many :corporations_electoral_lists, dependent: :destroy
    has_many :councillors_corporations, dependent: :destroy

    validates :name, uniqueness: true
    validates :name, :start_year, :end_year, presence: true

    scope :active, -> { where(active: true) }
    scope :inactive, -> { where(active: false) }

    accepts_nested_attributes_for :corporations_electoral_lists, :allow_destroy => true, reject_if: :all_blank
    accepts_nested_attributes_for :councillors_corporations, :allow_destroy => true, reject_if: :all_blank

    def self.main_columns
        [
            :name,
            :election_date,
            :full_constitutional_date,
            :end_corporation_date,
            :councillors_num,
            :active
        ]
    end

    def self.especific_columns
        %w{
            name
            election_date
            full_constitutional_date
            end_corporation_date
            councillors_num
            active_formated
            electoral_asociated
        }
    end

    def active_formated
        I18n.t("booleans.#{active}")
    end

    def electoral_asociated
        aux = ''
        corporations_electoral_lists.each do |cl|            
            aux = aux.blank? ? aux + cl.electoral_list.long_name : aux + ", " + cl.electoral_list.long_name
        end

        aux
    end

    def self.getNotificationData(notification)
        aux = ''
        corporation = self.transformData(notification)

        aux = aux + "<h1>Vista de corporación</h1><br>"
        aux = aux + "<fieldset><legend>Datos de corporación</legend><table><thead><tr>"
        [
            :name, :description, :start_year, :end_year, :election_date,   :full_constitutional_date,
            :end_corporation_date, :councillors_num,  :active
        ].each do |x|
            aux =  aux + "<th>#{Corporation.human_attribute_name(x)}</th>"
        end
        aux = aux + "</tr></thead><tbody><tr>"
        [
            :name, :description, :start_year, :end_year, :election_date,   :full_constitutional_date,
            :end_corporation_date, :councillors_num,  :active
        ].each do |x|
            aux =  aux + "<td>#{corporation.try(x)}</td>"
        end
        aux = aux + "</tr></tbody></table></fieldset><fieldset><legend>Afiliaciones</legend><table><thead><tr>"
        aux =  aux + "<th>#{ElectoralList.human_attribute_name(:name)}</th>"
        aux = aux + "</tr></thead><tbody>"
        corporation.corporations_electoral_lists.each do |l|
            aux =  aux + "<tr>"
            aux =  aux + "<td>#{l.electoral_list.try(:name)}</td>"
            aux =  aux + "</tr>"
        end
        aux = aux + "</tbody></table></fieldset>"

        aux.html_safe
    end
    
    

    def self.transformData(notification)
        corporation = Corporation.new(
            name: notification.try(:content_data).try{|x| x['cpNombre'].gsub('/','-')},
            description: notification.try(:content_data).try{|x| x['cpObserv']},
            active: notification.try(:content_data).try{|x| x['cpActiva']},
            end_year: notification.try(:content_data).try{|x| x['cpAnioFin']},
            start_year: notification.try(:content_data).try{|x| x['cpAnioInicio']},
            councillors_num: notification.try(:content_data).try{|x| x['cpNumConcej']},
            end_corporation_date: notification.try(:content_data).try{|x| x['cpFechaFinal']}.blank? ? '' : Time.at(notification.try(:content_data).try{|x| x['cpFechaFinal']}/1000).strftime("%d/%m/%Y"),
            election_date: notification.try(:content_data).try{|x| x['cpFechaElecciones']}.blank? ? '' : Time.at(notification.try(:content_data).try{|x| x['cpFechaElecciones']}/1000).strftime("%d/%m/%Y"),
            full_constitutional_date: notification.try(:content_data).try{|x| x['cpFechaPlenoConst']}.blank? ? '' : Time.at(notification.try(:content_data).try{|x| x['cpFechaPlenoConst']}/1000).strftime("%d/%m/%Y"),
        )

        if !notification.try(:content_data).try{|x| x['listasElectorales']}.blank?
            notification.try(:content_data).try{|x| x['listasElectorales']}.each do |l|
                aux_l = ElectoralList.find_by("long_name LIKE '%#{ l['leNombreLista']}%' OR name Like '%#{ l['leNombreLista']}%'")
                if aux_l.blank?
                    aux_l = ElectoralList.new(name: l['leNombreLista'], long_name: l['leNombreLista'])
                end
                aux_union = CorporationsElectoralList.create(corporation: corporation, electoral_list: aux_l)
                corporation.corporations_electoral_lists << aux_union                        
            end
        end

        corporation
    end
end

app/controllers/admin/corporations_controller.rb
class Admin::CorporationsController < Admin::BaseController
    before_action :load_data, only: [:new, :create, :edit, :update, :destroy]

    def index
        @corporations = Corporation.all.order(name: :asc)
    rescue => e
        begin
          Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end

    def new
    rescue => e
        begin
          Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end

    def edit
    rescue => e
        begin
          Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end

    def create
        @corporation.name = params_corporations[:start_year]+"-"+params_corporations[:end_year]
        @corporation.assign_attributes(params_corporations)
        if @corporation.save
            redirect_to admin_corporations_path, notice: I18n.t('admin.corporations.success_insert')
        else
            render :new
        end
    rescue => e
        begin
          Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end

    def update
        @corporation.name = params_corporations[:start_year]+"-"+params_corporations[:end_year]
        if @corporation.update(params_corporations)
            redirect_to admin_corporations_path, notice: I18n.t('admin.corporations.success_update')
        else
            render :edit
        end
    rescue => e
        begin
          Rails.logger.error("COD-00005: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end

    def destroy
        if @corporation.destroy
            redirect_to admin_corporations_path, notice: I18n.t('admin.corporations.success_destroy')
        else
            redirect_to admin_corporations_path, alert: I18n.t('admin.corporations.error_destroy')
        end
    rescue => e
        begin
          Rails.logger.error("COD-00006: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end

    private

    def params_corporations
        params.require(:corporation).permit(
            :name, 
            :election_date,
            :start_year, 
            :end_year, 
            :full_constitutional_date, 
            :end_corporation_date,
            :councillors_num,
            :descriptions,
            :active,
            {
              corporations_electoral_lists_attributes: [
                :id,
                :_destroy,
                :corporation_id,
                :electoral_list_id,
                :order
              ]
            })
    end

    def load_data
        @corporation = params[:id].blank? ? Corporation.new : Corporation.find(params[:id])
    end

end

app/views/admin/corporations/_form.html.erb
<%= render partial: "shared/errors", locals: {errors: f.object.errors, model: undescore(f.object.class.name)}%>

<div class="row">
    <div class="small-3 column">
        <%=f.input :name, label_html: { class: ("error" unless f.object.errors[:name].blank?) },
            input_html: {disabled: true, class: ("error" unless f.object.errors[:name].blank?) } %>
    </div>
    <div class="small-3 column">
        <%=f.input :start_year, label_html: { class: ("error" unless f.object.errors[:start_year].blank?) },
            input_html: { class: ("error" unless f.object.errors[:start_year].blank?) } %>
    </div>
    <div class="small-3 column">
        <%=f.input :end_year, label_html: { class: ("error" unless f.object.errors[:end_year].blank?) },
            input_html: { class: ("error" unless f.object.errors[:end_year].blank?) } %>
    </div>
    <div class="small-3 column">
        <% election_date = f.object.election_date.nil? ? '' : f.object.election_date.strftime("%Y-%m-%d") %>
        <%= f.input :election_date, as: :string, input_html: { value: election_date , type: 'date' }%>
    </div>
</div>
<div class="row">
    <div class="small-3 column">
        <% full_constitutional_date = f.object.full_constitutional_date.nil? ? '' : f.object.full_constitutional_date.strftime("%Y-%m-%d") %>
        <%= f.input :full_constitutional_date,as: :string, input_html: { value: full_constitutional_date , type: 'date'} %>
    </div>
    <div class="small-3 column">
        <% end_corporation_date = f.object.end_corporation_date.nil? ? '' : f.object.end_corporation_date.strftime("%Y-%m-%d") %>
        <%= f.input :end_corporation_date,as: :string, input_html: { value: end_corporation_date , type: 'date'} %>
    </div>
    <div class="small-3 column">
        <%=f.input :councillors_num %>
    </div>
    <div class="small-3 column">
        <%=f.input :active %>
    </div>
</div>
<div class="row">
    <div class="column">
        <fieldset>
        <legend><%=t('admin.corporations.electoral_lists')%></legend>           
            <div  class="row">
                <div class="small-6 column">
                    <%= label_tag(:electoral_list, "#{t('admin.corporations.electoral_list')}*") %>
                </div>
                <div class="small-3 column">
                    <%= label_tag(:order, t('admin.corporations.order')) %>
                </div>
                <div class="small-3 column">
                </div>
            </div>
            <div id="corporations_electoral_lists">
                <%= f.fields_for :corporations_electoral_lists  do |ce_list| %>
                    <div  class="row">
                        <div class="small-6 column">
                            <%= ce_list.association :electoral_list, label: false,
                                input_html: { class: ("error" unless ce_list.object.errors[:electoral_list].blank?) } %>
                        </div>
                        <div class="small-3 column">
                            <%= ce_list.input :order, label: false%>
                        </div>
                        <div class="small-3 column" >
                            <%= ce_list.link_to_remove t('shared.delete'), class: "delete", onclick: "reload_data_info(1)" %>
                        </div>
                    </div>
                <%end%>
            </div>
        <div class="row">
            <div class="column">
                <%= f.link_to_add t('shared.add'), :corporations_electoral_lists,:class => "right small button radius success", :data => { :target => "#corporations_electoral_lists" }, onclick: "reload_data_info(0)" %>
            </div>
        </div>
        </fieldset>
    </div>
</div>
    
<div class="actions">
    <%= link_to t('admin.actions.back'), admin_electoral_lists_path, class: "button radius" %>
    <%= f.button :submit, class: "button radius" %>
</div>

app/views/admin/corporations/edit.html.erb
<h1><%= t('admin.corporations.edit.title') %></h1>
<%= simple_nested_form_for @corporation, url: admin_corporation_path(@corporation), html: { multipart: true } do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/admin/corporations/index.html.erb
<h1><%= t('admin.corporations.index.title') %></h1>
<p>
    <div class="row">
        <div class="column">
            <%= link_to t('admin.corporations.index.new_action'), new_admin_corporation_path, class: 'button small radius ' %>
        </div>
    </div>
</p>
<table>
  <thead>
    <tr>
        <% Corporation.main_columns.each do |col|%>
            <th><%=Corporation.human_attribute_name(col)%></th>
        <%end%>
        <th><%= t("admin.people.headers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @corporations.each do |corp| %>
      <tr>
        <% Corporation.main_columns.each do |col|%>
            <td><%=col.to_s == "active" ? t("booleans.#{corp.try(col).to_s}") : corp.try(col)%></td>
        <%end%>
        <td>
          <%= link_to edit_admin_corporation_path(corp), alt: t('admin.actions.edit'),title:t('admin.actions.edit') do %>
            <i class="fa fa-pen fa-lg"></i>
          <%end%>
          <%= link_to admin_corporation_path(corp), class: "delete", method: :delete, data: {confirm: t("admin.corporations.confirm_deletion", corporation: corp.name)}, alt: t('admin.actions.delete'),title:t('admin.actions.delete') do %>
            <i class="fa fa-trash-alt fa-lg"></i>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/corporations/new.html.erb
<h1><%= t('admin.corporations.new.title') %></h1>
<%= simple_nested_form_for @corporation, url: admin_corporations_path, html: { multipart: true } do |f| %>
  <%= render 'form', f: f %>
<% end %>