config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, {
    skip: [:registrations]
  }
  #resources :home, only: [:index]
  if Rails.application.secrets.try(:maintenance).blank? || !Rails.application.secrets.maintenance
    root 'people#councillors'
  else
    root 'static_pages#maintance'
  end
  
  resources :people, only: [:index, :show] do
    member do
      post :contact
      put :hide
      put :unhide
    end
    collection do
      get :councillors
      get :councillors_not_work
      get :councillors_other
      get :directors
      get :directors_not_work
      get :temporary_workers
      get :public_workers
      get :labours
      get :spokespeople
    end
  end

  concern :mailer_log do
    get :show_mailer, on: :member
    post :send_mailer, on: :member
  end
  
  namespace :admin do
    resources :data_exports, only: [:index] 
    resources :notifications, only: [:show] do
      get :profiles, on: :collection
      get :assets, on: :collection
      get :activities, on: :collection
      get :person, on: :collection
      get :profiles_historic, on: :collection
      get :assets_historic, on: :collection
      get :activities_historic, on: :collection
      get :person_historic, on: :collection
      get :permit, on: :member
      get :reject, on: :member
      get :publicable, on: :member
      get :update_data, on: :collection
      get :insert_reject, on: :member
      get :forward, on: :member
    end
    resources :preferences, only: [:index]
    resources :manage_emails
    resources :data_preferences do
      post :update_all, on: :collection
    end
    root to: "dashboard#index"
    resources :text_contents
    resources :corporations
    resources :electoral_lists
    resources :delete_data, only: [:show, :index] do
      post :delete_information, on: :collection
    end
    resources :profile_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy]
    resources :assets_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :activities_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :people, except: :show do
      get :show_hide, on: :member
      get :show_unhide, on: :member
      get :portrait_delete, on: :member
      get :audits, on: :member
      put :hide
      put :unhide
      get :download, on: :collection
    end
    resources :statistics, only: [:index] do
      get :profiles, on: :collection
      get :councillors, on: :collection
      get :directors, on: :collection
      get :update_data, on: :collection
    end
  end

  # static pages
  #get "/welcome", to: "home#welcome"
  #get "/maintance", to: "static_pages#maintance"
  get "/accessibility", to: "static_pages#accessibility"
  get "/conditions", to: "static_pages#conditions"
  get "/privacy", to: "static_pages#privacy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect('/')
  get "*missing" => redirect('/') 
end

app/views/admin/_menu.html.erb
<nav class="admin-sidebar">
  <ul id="admin_menu">
    <li><%= link_to t('admin.menu.title'), admin_root_path %></li>

    <li class="<%= 'active' if controller_name == 'delete_data' %>">
      <%= link_to admin_delete_data_path do %>
        <i class="icon-deleted"></i>
        <%= t('admin.menu.delete_data') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'profile_uploads' %>">
      <%= link_to admin_profile_uploads_path do %>
        <i class="icon-document"></i>
        <%= t('admin.menu.profile_uploads') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'assets_uploads' %>">
      <%= link_to admin_assets_uploads_path do %>
        <i class="icon-document"></i>
        <%= t('admin.menu.assets_uploads') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'activities_uploads' %>">
      <%= link_to admin_activities_uploads_path do %>
        <i class="icon-document"></i>
        <%= t('admin.menu.activities_uploads') %>
      <% end %>
    </li>

     <li class="<%= 'active' if controller_name == 'data_exports' %>">
      <%= link_to admin_data_exports_path do %>
        <i class="icon-document"></i>
        <%= t('admin.menu.data_exports') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'people' %>">
      <%= link_to admin_people_path do %>
        <i class="icon-user"></i>
        <%= t('admin.menu.people') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'statistics' %>">
      <%= link_to profiles_admin_statistics_path do %>
        <i class="icon-stats"></i>
        <%= t('admin.menu.statistics') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'notifications' %>">
      <%= link_to person_admin_notifications_path do %>
        <i class="icon-letter"></i>
        <%= t('admin.menu.notifications', count: getNumberNotifications) %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'electoral_lists' %>">
      <%= link_to admin_electoral_lists_path do %>
        <i class="icon-settings"></i>
        <%= t('admin.menu.electoral_lists') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'corporations' %>">
      <%= link_to admin_corporations_path do %>
        <i class="icon-settings"></i>
        <%= t('admin.menu.corporations') %>
      <% end %>
    </li>

    <li class="<%= 'active' if controller_name == 'preferences' %>">
      <%= link_to admin_preferences_path do %>
        <i class="icon-settings"></i>
        <%= t('admin.menu.preferences') %>
      <% end %>
    </li>

    <li>
      <%= link_to destroy_administrator_session_path, class: "logout", method: 'delete' do %>
        <i class="icon-x"></i>
        <%= t('admin.menu.close_session') %>
      <% end %>
    </li>
  </ul>
</nav>