config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, {
    skip: [:registrations]
  }
  #resources :home, only: [:index]
  if Rails.application.secrets.try(:maintenance).blank? || !Rails.application.secrets.maintenance
    root 'people#councillors'
  else
    root 'static_pages#maintance'
  end
  
  resources :people, only: [:index, :show] do
    member do
      post :contact
      put :hide
      put :unhide
    end
    collection do
      get :councillors
      get :councillors_not_work
      get :councillors_other
      get :directors
      get :directors_not_work
      get :temporary_workers
      get :public_workers
      get :labours
      get :spokespeople
    end
  end

  concern :mailer_log do
    get :show_mailer, on: :member
    post :send_mailer, on: :member
  end
  
  namespace :admin do
    resources :data_exports, only: [:index] 
    resources :notifications, only: [:show] do
      get :profiles, on: :collection
      get :assets, on: :collection
      get :activities, on: :collection
      get :person, on: :collection
      get :profiles_historic, on: :collection
      get :assets_historic, on: :collection
      get :activities_historic, on: :collection
      get :person_historic, on: :collection
      get :permit, on: :member
      get :reject, on: :member
      get :publicable, on: :member
      get :update_data, on: :collection
      get :insert_reject, on: :member
      get :forward, on: :member
    end
    resources :preferences, only: [:index]
    resources :manage_emails
    resources :data_preferences do
      post :update_all, on: :collection
    end
    root to: "dashboard#index"
    resources :text_contents
    resources :corporations
    resources :electoral_lists
    resources :delete_data, only: [:show, :index] do
      post :delete_information, on: :collection
    end
    resources :profile_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy]
    resources :assets_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :activities_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :people, except: :show do
      get :show_hide, on: :member
      get :show_unhide, on: :member
      get :portrait_delete, on: :member
      get :audits, on: :member
      put :hide
      put :unhide
      get :download, on: :collection
    end
    resources :statistics, only: [:index] do
      get :profiles, on: :collection
      get :councillors, on: :collection
      get :directors, on: :collection
      get :update_data, on: :collection
    end
  end

  # static pages
  #get "/welcome", to: "home#welcome"
  #get "/maintance", to: "static_pages#maintance"
  get "/accessibility", to: "static_pages#accessibility"
  get "/conditions", to: "static_pages#conditions"
  get "/privacy", to: "static_pages#privacy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect('/')
  get "*missing" => redirect('/') 
end

app/helpers/admin/statistics_helper.rb
module Admin
  module StatisticsHelper
    extend ActiveSupport::Concern

    def self.file_name(year=nil, corporation=nil)
      {
        'profiles' => {
          'councillor' => {'all' => 'concejales_activos', 'profile' => 'concejales_con_perfil', 'unprofile' => 'concejales_sin_perfil'},
          'director' => {'all' => 'directivos_activos', 'profile' => 'directivos_con_perfil', 'unprofile' => 'directivos_sin_perfil'},
          'public_worker' => {'all' => 'funcionarios_activos', 'profile' => 'funcionarios_con_perfil', 'unprofile' => 'funcionarios_sin_perfil'},
          'temporary_worker' => {'all' => 'eventuales_activos', 'profile' => 'eventuales_con_perfil', 'unprofile' => 'eventuales_sin_perfil'},
          'spokesperson' => {'all' => 'vocales_vecinos_activos', 'profile' => 'vocales_vecinos_con_perfil', 'unprofile' => 'vocales_vecinos_sin_perfil'},
          'total' => {'all' => 'total_activos', 'profile' => 'total_con_perfil', 'unprofile' => 'total_sin_perfil'}
        },
        'directors' => {
          'active' => {
            'inicial' => {
              'asset' => { 'all' => 'directivos_act_bienes_inicial', 'with' => 'directivos_act_bienes_inicial_obligado', 'without' => 'directivos_act_bienes_inicial_no_obligado'},
              'activity' => { 'all' => 'directivos_act_activi_inicial', 'with' => 'directivos_act_activi_inicial_obligado', 'without' => 'directivos_act_activid_inicial_no_obligado'}
            },
            'final' => {
              'asset' => { 'all' => 'directivos_act_bienes_final', 'with' => 'directivos_act_bienes_final_obligado', 'without' => 'directivos_act_bienes_final_no_obligado'},
              'activity' => { 'all' => 'directivos_act_activi_final', 'with' => 'directivos_act_activi_final_obligado', 'without' => 'directivos_act_activid_final_no_obligado'}
            },
            'anual' => {
              'asset' => { 'all' => "directivos_act_bienes_#{year.to_s}", 'with' => "directivos_act_bienes_obligado_#{year.to_s}", 'without' => "directivos_act_bienes_no_obligado_#{year.to_s}"},
              'activity' => { 'all' => "directivos_act_activi_#{year.to_s}", 'with' => "directivos_act_activi_obligado_#{year.to_s}", 'without' => "directivos_act_activid_no_obligado_#{year.to_s}"}
            }
          },
          'inactive' => {
            'inicial' => {
              'asset' => {'all' => 'directivos_ina_bienes_inicial', 'with' => 'directivos_ina_bienes_inicial_obligado', 'without' => 'directivos_ina_bienes_inicial_no_obligado'},
              'activity' => {'all' => 'directivos_ina_activi_inicial', 'with' => 'directivos_ina_activi_inicial_obligado', 'without' => 'directivos_ina_activid_inicial_no_obligado'}
            },
            'final' => {
              'asset' => {'all' => 'directivos_ina_bienes_final', 'with' => 'directivos_ina_bienes_final_obligado', 'without' => 'directivos_ina_bienes_final_no_obligado'},
              'activity' => { 'all' => 'directivos_ina_activi_final', 'with' => 'directivos_ina_activi_final_obligado', 'without' => 'directivos_ina_activid_final_no_obligado'}
            },
            'anual' => {
              'asset' => {'all' => "directivos_ina_bienes_#{year.to_s}", 'with' => "directivos_ina_bienes_obligado_#{year.to_s}", 'without' => "directivos_ina_bienes_no_obligado_#{year.to_s}"},
              'activity' => {'all' => "directivos_ina_activi_#{year.to_s}", 'with' => "directivos_ina_activi_obligado_#{year.to_s}", 'without' => "directivos_ina_activid_no_obligado_#{year.to_s}"}
            }
          }
        },
        'corporation' => {
          'active' => {
            'inicial' => {
              'asset' => { 'all' => "#{corporation}_concejales_act_bienes_inicial", 'with' => "#{corporation}_concejales_act_bienes_inicial_obligado", 'without' => "#{corporation}_concejales_act_bienes_inicial_no_obligado"},
              'activity' => { 'all' => "#{corporation}_concejales_act_activi_inicial", 'with' => "#{corporation}_concejales_act_activi_inicial_obligado", 'without' => "#{corporation}_concejales_act_activid_inicial_no_obligado"}
            },
            'final' => {
              'asset' => { 'all' => "#{corporation}_concejales_act_bienes_final", 'with' => "#{corporation}_concejales_act_bienes_final_obligado", 'without' => "#{corporation}_concejales_act_bienes_final_no_obligado"},
              'activity' => { 'all' => "#{corporation}_concejales_act_activi_final", 'with' => "#{corporation}_concejales_act_activi_final_obligado", 'without' => "#{corporation}_concejales_act_activid_final_no_obligado"}
            },
            'anual' => {
              'asset' => { 'all' => "#{corporation}_concejales_act_bienes_#{year.to_s}", 'with' => "#{corporation}_concejales_act_bienes_obligado_#{year.to_s}", 'without' => "#{corporation}_concejales_act_bienes_no_obligado_#{year.to_s}" },
              'activity' => { 'all' => "#{corporation}_concejales_act_activi_#{year.to_s}", 'with' => "#{corporation}_concejales_act_activi_obligado_#{year.to_s}", 'without' => "#{corporation}_concejales_act_activid_no_obligado_#{year.to_s}"}
            }
          },
          'inactive' => {
            'inicial' => {
              'asset' => { 'all' => "#{corporation}_concejales_ina_bienes_inicial", 'with' => "#{corporation}_concejales_ina_bienes_inicial_obligado", 'without' => "#{corporation}_concejales_ina_bienes_inicial_no_obligado"},
              'activity' => {'all' => "#{corporation}_concejales_ina_activi_inicial", 'with' => "#{corporation}_concejales_ina_activi_inicial_obligado", 'without' => "#{corporation}_concejales_ina_activid_inicial_no_obligado"}
            },
            'final' => {
              'asset' => { 'all' => "#{corporation}_concejales_ina_bienes_final", 'with' => "#{corporation}_concejales_ina_bienes_final_obligado", 'without' => "#{corporation}_concejales_ina_bienes_final_no_obligado" },
              'activity' => { 'all' => "#{corporation}_concejales_ina_activi_final", 'with' => "#{corporation}_concejales_ina_activi_final_obligado", 'without' => "#{corporation}_concejales_ina_activid_final_no_obligado" }
            },
            'anual' => {
              'asset' => { 'all' => "#{corporation}_concejales_ina_bienes_#{year.to_s}", 'with' => "#{corporation}_concejales_ina_bienes_obligado_#{year.to_s}", 'without' => "#{corporation}_concejales_ina_bienes_no_obligado_#{year.to_s}"},
              'activity' => { 'all' => "#{corporation}_concejales_ina_activi_#{year.to_s}", 'with' => "#{corporation}_concejales_ina_activi_obligado_#{year.to_s}", 'without' => "#{corporation}_concejales_ina_activid_no_obligado_#{year.to_s}"}
            }
          }
        }
      }
    rescue => e
      begin
        Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    #####################################################################################################################
    ## COUNCILLORS
    #####################################################################################################################
    def stream_query_rows_councillors(active, declaration, temporality, part, corporation, editable)
      preference_interval = DataPreference.find_by(:code => "public_year")
      year_interval= preference_interval.blank? ? 2 : preference_interval.type_data.to_i==0 ? preference_interval.content_data.to_i : 2
      data_where = ''

      if !editable.blank? && editable.to_s == "true"
        data_where = data_where + " AND (((d.declaration_type ='AssetsDeclaration' AND d.declaration_id in (select ad.id from assets_declarations ad where ad.editable=true)) OR (d.declaration_type ='ActivitiesDeclaration' AND d.declaration_id in (select ad.id from activities_declarations ad where ad.editable=true))))"
      else
        data_where = data_where + " AND (d.declaration_id is null or ((d.declaration_type ='AssetsDeclaration' AND d.declaration_id not in (select ad.id from assets_declarations ad where ad.editable=true)) OR (d.declaration_type ='ActivitiesDeclaration' AND d.declaration_id not in (select ad.id from activities_declarations ad where ad.editable=true))))"
      end

      if editable.blank? || editable.to_s != "true"
        if !active.blank? && active.to_s=="true"
          data_where = data_where + " AND (cc.appointment_id in (select  a.id from appointments a where a.end_date is null or cast(a.end_date as date) > cast(NOW() as date)) or cc.appointment_id is null)"
        else
          data_where = data_where + " AND (cc.appointment_id not in (select  a.id from appointments a where a.end_date is null or cast(a.end_date as date) > cast(NOW() as date)) and cc.appointment_id is not null)"
        end
      end

      if !temporality.blank?
        data_where = data_where + " AND (d.temporality_id in (select t.id from temporalities t where t.name = '#{temporality.include?("Anual") ? 'Anual'.strip : temporality.strip}') #{"AND d.year = '#{temporality.gsub(" ","").split('-')[1]}'" if temporality.include?("Anual") })"
      end
      data_where = data_where + " AND d.declaration_id is not null" if ['with', 'editable'].include?(part)
      data_where = data_where + " AND d.declaration_id is null" if ['without'].include?(part)

      sqldata= "select
      COALESCE(CAST(p.personal_code as varchar), '-') as \"Identificador\",
      COALESCE(CAST(to_char(jl.updated_at,'dd/MM/yyyy HH24:MI') as varchar),'-') as \"Fecha de actualización\",
      COALESCE(p.last_name,'-')  as \"Apellidos\",
      COALESCE(p.name,'-')  as \"Nombre\",
      CASE jl.person_type WHEN 'director' THEN 'Personal directivo'
              WHEN 'public_worker' THEN 'Personal funcionario'
              WHEN 'temporary_worker' THEN 'Personal eventual'
              WHEN 'spokesperson' THEN 'Vocal vecino' ELSE 'otro' end as \"Tipo persona\",
      COALESCE((select CASE WHEN a.end_date IS NULL THEN 'Activo'

app/views/admin/statistics/_corporation.html.erb
<div class="row">
    <div class="small-6 column">
        <%= radio_button_tag("export[councillors_#{corporation}]",:csv,(params[:export].blank? || params[:export]=="csv"), :onclick => "change_param_parametrize_url(['export', 'csv'], 'statistics/?councillors=true&corporation=#{corporation}','#recarga_corporation_#{corporation}')") %>
        <%= label_tag(:export_csv, t('admin.dashboard.form.export_csv')) %>
    </div>
    <div class="small-6 column">
        <%= radio_button_tag("export[councillors_#{corporation}]",:xls,(params[:export]=="xls"), :onclick => "change_param_parametrize_url(['export', 'xls'], 'statistics/?councillors=true&corporation=#{corporation}','#recarga_corporation_#{corporation}')") %>
        <%= label_tag(:export_xls, t('admin.dashboard.form.export_xls')) %>
    </div>
</div>
<div id="recarga_corporation_<%=corporation%>">
    <h3><%= t('admin.menu.active_councillors') %></h3><br>
    <table>
        <thead>
            <tr>
                <th><%= t("admin.menu.period") %></th>
                <th><%= t("admin.menu.type_declaration") %></th>
                <th><%= t("admin.menu.duties") %></th>
                <th><%= t("admin.menu.with") %></th>
                <th><%= t("admin.menu.without") %></th>
            </tr>
        </thead>
        <tbody>
            <%@data_councillors_active.select {|a| a[:corporation] == corporation}.each do |data|%>
                <tr>
                    <td><strong><%=data[:temporality]%></strong></td>
                    <td><strong><%=t(data[:declaration])%></strong></td>
                    <% [:all, :with, :without].each do |t|%>
                        <td>
                           <% if data[t] > 0 && data[:declaration].to_s != 'Total'%>
                                <%= link_to data[t], current_url(params.merge(:format=> params[:export].blank? ? "csv" : params[:export], section: 'corporation', corporation: corporation, active: true, temporality: data[:temporality], declaration: data[:declaration], part: t)) %>
                            <% else %>
                                <%= data[t] %>
                            <% end %>
                        </td>
                    <%end%>
                </tr>
            <% end  %>
        </tbody>
    </table>

    <br><h3><%= t('admin.menu.inactive_councillors') %></h3><br>
    <table>
        <thead>
            <tr>
                <th><%= t("admin.menu.period") %></th>
                <th><%= t("admin.menu.type_declaration") %></th>
                <th><%= t("admin.menu.duties") %></th>
                <th><%= t("admin.menu.with") %></th>
                <th><%= t("admin.menu.without") %></th>
            </tr>
        </thead>
        <tbody>
             <%@data_councillors_inactive.select {|a| a[:corporation] == corporation}.each do |data|%>
                <tr>
                    <td><strong><%=data[:temporality]%></strong></td>
                    <td><strong><%=t(data[:declaration])%></strong></td>
                    <% [:all, :with, :without].each do |t|%>
                        <td>
                            <% if data[t] > 0 && data[:declaration].to_s != 'Total'%>
                                <%= link_to data[t], current_url(params.merge(:format=> params[:export].blank? ? "csv" : params[:export], section: 'corporation', corporation: corporation, temporality: data[:temporality], declaration: data[:declaration], part: t)) %>
                            <% else %>
                                <%= data[t] %>
                            <% end %>
                        </td>
                    <%end%>
                </tr> 
            <% end  %>
        </tbody>
    </table>

    <br><h3><%= t('admin.menu.editable_councillors') %></h3><br>
    <table>
        <thead>
            <tr>
                <th><%= t("admin.menu.period") %></th>
                <th><%= t("admin.menu.type_declaration") %></th>
                <th><%= t("admin.menu.duties") %></th>
                <th><%= t("admin.menu.editable") %></th>
            </tr>
        </thead>
        <tbody>
             <%@data_councillors_editable.select {|a| a[:corporation] == corporation}.each do |data|%>
                <tr>
                    <td><strong><%=data[:temporality]%></strong></td>
                    <td><strong><%=t(data[:declaration])%></strong></td>
                    <% [:all, :editable].each do |t|%>
                        <td>
                            <% if data[t] > 0 && data[:declaration].to_s != 'Total'%>
                                <%= link_to data[t], current_url(params.merge(:format=> params[:export].blank? ? "csv" : params[:export], section: 'corporation', corporation: corporation, temporality: data[:temporality], declaration: data[:declaration], part: t, editable: true)) %>
                            <% else %>
                                <%= data[t] %>
                            <% end %>
                        </td>
                    <%end%>
                </tr> 
            <% end  %>
        </tbody>
    </table>
</div>

app/views/admin/statistics/_councillors.html.erb
<h2><%= t('admin.menu.councillors') %></h2>
<br>

<ul class="tabs" data-tab>
    <% Corporation.all.order(name: :desc).each_with_index do |c, i|%>
        <li id="data_log" class="tab-title <%= "active" if params[:corporation].to_i == c.id || params[:corporation].blank? && i == 0%>">
            <a href="#corporation_<%= c.id %>"><%= c.name %></a>
        </li>
    <% end %>
</ul>

<div class="tabs-content">
    <% Corporation.all.order(name: :desc).each_with_index do |c, i|%>
        <div id="corporation_<%= c.id %>" class="small-12 column content <%= "active" if params[:corporation].to_i == c.id || params[:corporation].blank? && i == 0%>" aria-hidden="<%= !(params[:corporation] == c.id || params[:corporation].blank? && i == 0) || true%>">
            <%=render "corporation", corporation: c.id%>
        </div>
    <% end %>
</div>

app/views/admin/statistics/_directors.html.erb
<div class="row">
    <div class="small-6 column">
        <%= radio_button_tag("export[directors]",:csv,(params[:export].blank? || params[:export]=="csv"), :onclick => "change_param_parametrize_url(['export', 'csv'], 'statistics/?directors=true','#recarga_directors')") %>
        <%= label_tag(:export_csv, t('admin.dashboard.form.export_csv')) %>
    </div>
    <div class="small-6 column">
        <%= radio_button_tag("export[directors]",:xls,(params[:export]=="xls"), :onclick => "change_param_parametrize_url(['export', 'xls'], 'statistics/?directors=true','#recarga_directors')") %>
        <%= label_tag(:export_xls, t('admin.dashboard.form.export_xls')) %>
    </div>
</div>
<h2><%= t('admin.menu.directors') %></h2>
<br>

<div id="recarga_directors">
    <h3><%= t('admin.menu.active_directors') %></h3><br>
    <table>
        <thead>
            <tr>
                <th><%= t("admin.menu.period") %></th>
                <th><%= t("admin.menu.type_declaration") %></th>
                <th><%= t("admin.menu.duties") %></th>
                <th><%= t("admin.menu.with") %></th>
                <th><%= t("admin.menu.without") %></th>
            </tr>
        </thead>
        <tbody>
            <%@data_directors_active.each do |data| %>
                <tr>
                    <td><strong><%=data[:temporality]%></strong></td>
                    <td><strong><%=t(data[:declaration])%></strong></td>
                    <% [:all, :with, :without].each do |t|%>
                        <td>
                            <% if data[t] > 0 && data[:declaration].to_s != 'Total'%>
                                <%= link_to data[t], current_url(params.merge(:format=> params[:export].blank? ? "csv" : params[:export], section: 'directors', active: true, temporality: data[:temporality], declaration: data[:declaration], part: t)) %>
                            <% else %>
                                <%= data[t] %>
                            <% end %>
                        </td>
                    <%end%>
                </tr> 
            <% end %>
        </tbody>
    </table>

    <br><h3><%= t('admin.menu.inactive_directors') %></h3><br>
    <table>
        <thead>
            <tr>
                <th><%= t("admin.menu.period") %></th>
                <th><%= t("admin.menu.type_declaration") %></th>
                <th><%= t("admin.menu.duties") %></th>
                <th><%= t("admin.menu.with") %></th>
                <th><%= t("admin.menu.without") %></th>
            </tr>
        </thead>
       <tbody>
            <%@data_directors_inactive.each do |data| %>
                <tr>
                    <td><strong><%=data[:temporality]%></strong></td>
                    <td><strong><%=t(data[:declaration])%></strong></td>
                    <% [:all, :with, :without].each do |t|%>
                        <td>
                            <% if data[t] > 0 && data[:declaration].to_s != 'Total'%>
                                <%= link_to data[t], current_url(params.merge(:format=> params[:export].blank? ? "csv" : params[:export], section: 'directors', temporality: data[:temporality], declaration: data[:declaration], part: t)) %>
                            <% else %>
                                <%= data[t] %>
                            <% end %>
                        </td>
                    <%end%>
                </tr> 
            <% end %>
        </tbody>
    </table>

    <br><h3><%= t('admin.menu.editable_directors') %></h3><br>
    <table>
        <thead>
            <tr>
                <th><%= t("admin.menu.period") %></th>
                <th><%= t("admin.menu.type_declaration") %></th>
                <th><%= t("admin.menu.duties") %></th>
                <th><%= t("admin.menu.editable") %></th>
            </tr>
        </thead>
       <tbody>
            <%@data_directors_editable.each do |data| %>
                <tr>
                    <td><strong><%=data[:temporality]%></strong></td>
                    <td><strong><%=t(data[:declaration])%></strong></td>
                    <% [:all, :editable].each do |t|%>
                        <td>
                            <% if data[t] > 0 && data[:declaration].to_s != 'Total'%>
                                <%= link_to data[t], current_url(params.merge(:format=> params[:export].blank? ? "csv" : params[:export], section: 'directors', temporality: data[:temporality], declaration: data[:declaration], part: t, editable: true)) %>
                            <% else %>
                                <%= data[t] %>
                            <% end %>
                        </td>
                    <%end%>
                </tr> 
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/statistics/_menu_statistics.html.erb
<div class="row">
  <div class="small-6 column">
    <h1><%= t('admin.menu.statistics') %></h1>
  </div>
  <div class="small-6 column text-right">
    <%= link_to t('statistics.update_data'), update_data_admin_statistics_path, data: {confirm: t('statistics.confirm_update')}, class: 'button small radius ' %>
  </div>
</div>
<br>

<ul class="tabs">
  <li id="data_log" class="tab-title <%= "active" if type.blank? || type == "profiles"%>">
    <%= link_to t('profile.statistics_profiles'), profiles_admin_statistics_path %>
  </li>
  <li id="data_log" class="tab-title <%= "active" if type == "councillors"%>">
    <%= link_to t('profile.statistics_councillors'), councillors_admin_statistics_path %>
  </li>
  <li id="data_log" class="tab-title <%= "active" if type == "directors"%>">
    <%= link_to t('profile.statistics_director'), directors_admin_statistics_path %>
  </li>
</ul>

<div class="tabs-content">
  <div class="small-12 column content active" aria-hidden="false">
    <%=render "#{type.blank? ? "profiles" : type}"%>
  </div> 
</div>

app/views/admin/statistics/_profiles.html.erb
<div class="row">
    <div class="small-6 column">
        <%= radio_button_tag("export[profiles]",:csv,(params[:export].blank? || params[:export]=="csv"), :onclick => "change_param_parametrize_url(['export', 'csv'], 'statistics/?profiles=true', '#recarga_profiles')") %>
        <%= label_tag(:export_csv, t('admin.dashboard.form.export_csv')) %>
    </div>
    <div class="small-6 column">
        <%= radio_button_tag("export[profiles]",:xls,(params[:export]=="xls"), :onclick => "change_param_parametrize_url(['export', 'xls'], 'statistics/?profiles=true', '#recarga_profiles')") %>
        <%= label_tag(:export_xls, t('admin.dashboard.form.export_xls')) %>
    </div>
</div>
<h2><%= t('admin.menu.profiles') %></h2>
<br>

<div id="recarga_profiles">
    <table>
        <thead>
            <tr>
                <th><%= t("admin.menu.person") %></th>
                <th><%= t("admin.menu.n_active") %></th>
                <th><%= t("admin.menu.profile_published") %></th>
                <th><%= t("admin.menu.without_profile_published") %></th>
            </tr>
        </thead>
        <tbody>
            <% @profiles_count.each do |item|%>
                <tr>
                    <td><strong><%= t("admin.dashboard.#{item[:type]}") %></strong></td>
                    <% [:all, :profile, :unprofile].each do |t|%>
                        <td>
                            <% if item[t] > 0%>
                                <%= link_to item[t], current_url(params.merge(:format=> params[:export].blank? ? "csv" : params[:export], section: 'profiles', person: item[:type], part: t)) %>
                            <% else %>
                                <%= item[t] %>
                            <% end %>
                        </td>
                    <%end%>
                </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/admin/statistics/councillors.html.erb
 <%=render "menu_statistics", type: "councillors"%>

app/views/admin/statistics/directors.html.erb
 <%=render "menu_statistics", type: "directors"%>

app/views/admin/statistics/profiles.html.erb
 <%=render "menu_statistics", type: "profiles"%>