config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, {
    skip: [:registrations]
  }
  #resources :home, only: [:index]
  if Rails.application.secrets.try(:maintenance).blank? || !Rails.application.secrets.maintenance
    root 'people#councillors'
  else
    root 'static_pages#maintance'
  end
  
  resources :people, only: [:index, :show] do
    member do
      post :contact
      put :hide
      put :unhide
    end
    collection do
      get :councillors
      get :councillors_not_work
      get :councillors_other
      get :directors
      get :directors_not_work
      get :temporary_workers
      get :public_workers
      get :labours
      get :spokespeople
    end
  end

  concern :mailer_log do
    get :show_mailer, on: :member
    post :send_mailer, on: :member
  end
  
  namespace :admin do
    resources :data_exports, only: [:index] 
    resources :notifications, only: [:show] do
      get :profiles, on: :collection
      get :assets, on: :collection
      get :activities, on: :collection
      get :person, on: :collection
      get :profiles_historic, on: :collection
      get :assets_historic, on: :collection
      get :activities_historic, on: :collection
      get :person_historic, on: :collection
      get :permit, on: :member
      get :reject, on: :member
      get :publicable, on: :member
      get :update_data, on: :collection
      get :insert_reject, on: :member
      get :forward, on: :member
    end
    resources :preferences, only: [:index]
    resources :manage_emails
    resources :data_preferences do
      post :update_all, on: :collection
    end
    root to: "dashboard#index"
    resources :text_contents
    resources :corporations
    resources :electoral_lists
    resources :delete_data, only: [:show, :index] do
      post :delete_information, on: :collection
    end
    resources :profile_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy]
    resources :assets_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :activities_uploads, concerns: :mailer_log, except: [:edit, :update, :destroy] do
      post :export,on: :collection
    end
    resources :people, except: :show do
      get :show_hide, on: :member
      get :show_unhide, on: :member
      get :portrait_delete, on: :member
      get :audits, on: :member
      put :hide
      put :unhide
      get :download, on: :collection
    end
    resources :statistics, only: [:index] do
      get :profiles, on: :collection
      get :councillors, on: :collection
      get :directors, on: :collection
      get :update_data, on: :collection
    end
  end

  # static pages
  #get "/welcome", to: "home#welcome"
  #get "/maintance", to: "static_pages#maintance"
  get "/accessibility", to: "static_pages#accessibility"
  get "/conditions", to: "static_pages#conditions"
  get "/privacy", to: "static_pages#privacy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect('/')
  get "*missing" => redirect('/') 
end

app/models/data_preference.rb
class DataPreference < ActiveRecord::Base
end

app/controllers/admin/data_preferences_controller.rb
class Admin::DataPreferencesController < Admin::BaseController
  def update_all
    returned_success=true
    data_preference_params[:info].each do |k,v|
      preference = DataPreference.find(v[:id])
      unless preference.blank?
        preference.content_data = v[:content_data]
        unless preference.save
          returned_success=false
          break
        end
      end
    end
   
    if returned_success
      `whenever -i cellar`
      redirect_to admin_preferences_path(generic: true), notice: I18n.t('data_preference.flash.success')
    else
      redirect_to admin_preferences_path(generic: true), alert: I18n.t('data_preference.flash.error')
    end
  rescue => e
    begin
      Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end


  private
    def data_preference_params
      params.require(:datas).permit({
        info: [
          :id,
          :content_data
        ]
      })
    end
end

app/helpers/data_preferences_helper.rb
module DataPreferencesHelper
    def get_type_preference(type=nil)
        return "" if type.blank?
        I18n.t("data_preference.types.#{type}")
    rescue => e
        begin
          Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end

    def type_preference(type=nil)
        return :string if type.blank?
        case type.to_s
        when "0"
            :integer
        when "1"
            :string
        when "2"
            :boolean
        when "3"
            :date
        else
            :string
        end
    rescue => e
        begin
          Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
        rescue
        end
    end
end

app/views/admin/data_preferences/_form.html.erb
<%= simple_form_for(@data_preference) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/data_preferences/edit.html.erb
<h1>Editing Data Preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_preference %> |
<%= link_to 'Back', data_preferences_path %>

app/views/admin/data_preferences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Data Preferences</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_preferences.each do |data_preference| %>
      <tr>
        <td><%= link_to 'Show', data_preference %></td>
        <td><%= link_to 'Edit', edit_data_preference_path(data_preference) %></td>
        <td><%= link_to 'Destroy', data_preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data preference', new_data_preference_path %>

app/views/admin/data_preferences/new.html.erb
<h1>New Data Preference</h1>

<%= render 'form' %>

<%= link_to 'Back', data_preferences_path %>

app/views/admin/data_preferences/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_data_preference_path(@data_preference) %> |
<%= link_to 'Back', data_preferences_path %>